import os
import numpy as np
import pandas as pd
configfile: "config.yml"

samples = pd.read_csv(config["manifest"], index_col=0)
script_dir = config["scripts_loc"] 

rule all:
  input: 
    contam=expand("output/{sample}.contamination.csv", sample=samples.index.tolist()),
    alignm=expand("output/{sample}.callstats.csv", sample=samples.index.tolist())
  output:
    txt="output/all.csv"
  run: 
    q = {x:pd.read_csv(x, index_col=0) for x in input}
    z = pd.concat(q).sort_values("pc_contam")
    z.to_csv(output.txt)


rule estimate_contamination:
  input:
    input=lambda y: samples.path.loc[y.sample],
    sites=config["genotyped_sites"],
    allele_frequencies=config["allele_frequencies"]
  output:
    txt="output/{sample}.contamination.csv"
  params:
    stem="output/{sample}",
    seqid=config["seqid_contam"],
    downsample=config["downsample"],
    minimum_af=config["minimum_af"],
    minimum_coverage=config["minimum_coverage"],
    seq_err_rate=config["ser"],
    plot=True,
    log=False
  script: 
    os.path.join(config["scripts_loc"], "estimate_contamination.py")


rule coverage_summary:
  input:
    input=lambda y: samples.path.loc[y.sample],
  output:
    csv="output/{sample}.callstats.csv",
    npy="output/{sample}.covhist.npz"
  params:
    stem="output/{sample}",
    seqid=config["seqid_stats"]
  script: 
    os.path.join(config["scripts_loc"], "calculate_alignment_summary_stats.py")


rule combine_individual_outputs_apply_qc_filters:
  input:
    manifest=config["manifest"],
    csv=expand("output/{sample}.callstats.csv", sample=samples.index.tolist()),
    npy=expand("output/{sample}.covhist.npz", sample=samples.index.tolist()),
    contam=expand("output/{sample}.contamination.csv", sample=samples.index.tolist())
  params:
    min_fgc=config["min_fgc"],
    min_med_cov=config["min_med_cov"],
    min_female_xratio=config["min_female_xratio"],
    max_male_xratio=config["max_male_xratio"],
    max_pc_contam=config["max_pc_contam"],
    path=lambda y: "output/{sample}"
  output:
    csv="output/qc_summary.csv"
  script:
    os.path.join(config["scripts_loc"], "combine_qc_cohort_stats.py")
    

