# which chromosomes to calculate pwd
pwd_contigs: ["3L", "3R", "X", "2L", "2R"]

# sites at which samples have been genotyped
genotyped_sites: /kwiat/vector/observatory/resources/agam/ag.allsites.nonN.zarr.zip

biallelic_sites: /kwiat/vector/ag1000g/release/phase2.AR1/variation/main/zarr2/ag1000g.phase2.ar1.pass.biallelic

# input/zip zarrs (for both contamination and alignment summary)
input_location: /kwiat/vector/mirror/observatory/vo_agam/genotype_zarrs

# suffix to append to the derived sample id to get zip zarr sample name
gt_suffix: ".zarr.zip"
